# Copyright 2026 Sentinel Foundation. All Rights Reserved.
#
# Licensed under the SENTINEL License Agreement. See LICENSE file in the project
# root for full terms.


from shared.errors.exceptions import (
    ActorError,
    ActorNotFoundError,
    AuditChainBrokenError,
    AuditError,
    AuditTamperedError,
    AuthError,
    DecayError,
    DuplicateEventError,
    EventError,
    InsufficientScopeError,
    InvalidApiKeyError,
    InvalidEventError,
    LlmError,
    LlmRateLimitedError,
    LlmTimeoutError,
    LlmUnavailableError,
    PatternError,
    PatternExecutionError,
    PatternNotFoundError,
    RateLimitedError,
    ScoreOutOfRangeError,
    ScoringError,
    SentinelError,
    ServiceDegradedError,
    TenantError,
    TenantNotFoundError,
    TenantQuotaExceededError,
    ValidationError,
)

__all__ = [
    "ActorError",
    "ActorNotFoundError",
    "AuditChainBrokenError",
    "AuditError",
    "AuditTamperedError",
    "AuthError",
    "DecayError",
    "DuplicateEventError",
    "EventError",
    "InsufficientScopeError",
    "InvalidApiKeyError",
    "InvalidEventError",
    "LlmError",
    "LlmRateLimitedError",
    "LlmTimeoutError",
    "LlmUnavailableError",
    "PatternError",
    "PatternExecutionError",
    "PatternNotFoundError",
    "RateLimitedError",
    "ScoreOutOfRangeError",
    "ScoringError",
    "SentinelError",
    "ServiceDegradedError",
    "TenantError",
    "TenantNotFoundError",
    "TenantQuotaExceededError",
    "ValidationError",
]
